spring:
  profiles:
    active: test

---
spring:
  datasource:
    url: jdbc:mysql://10.122.2.25:3306/web_rec_auto_test
    username: root
    password: XWzl!@#123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: test
